version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./mysql/my.conf:/etc/mysql/my.conf:ro
      - ./mysql/data:/var/lib/mysql
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "coolboy@88"
      MYSQL_DATABASE: "rlog"
    ports:
      - "13306:3306"